import { TeamAbbreviation } from "@/lib/transformTeamName";

export type Params<T extends Record<string, string>> = {
  params: T;
};

//Standings
export type Standing = {
  Season: number;
  SeasonType: number;
  TeamID: number;
  Key: string;
  City: string;
  Name: string;
  Conference: string;
  Division: string;
  Wins: number;
  Losses: number;
  Percentage: number;
  ConferenceWins: number;
  ConferenceLosses: number;
  DivisionWins: number;
  DivisionLosses: number;
  HomeWins: number;
  HomeLosses: number;
  AwayWins: number;
  AwayLosses: number;
  LastTenWins: number;
  LastTenLosses: number;
  PointsPerGameFor: number;
  PointsPerGameAgainst: number;
  Streak: number;
  GamesBack: number;
  StreakDescription: string;
  GlobalTeamID: number;
  ConferenceRank: number;
  DivisionRank: number;
};

export type SeriesInfo = {
  HomeTeamWins: number;
  AwayTeamWins: number;
  GameNumber: number;
  MaxLength: number;
};

//ScoresBasic
export type GameScore = {
  GameID: number;
  Season: number;
  SeasonType: number;
  Status: string;
  Day: string;
  DateTime: string;
  AwayTeam: string;
  HomeTeam: string;
  AwayTeamID: number;
  HomeTeamID: number;
  StadiumID: number;
  AwayTeamScore: number;
  HomeTeamScore: number;
  Updated: string;
  GlobalGameID: number;
  GlobalAwayTeamID: number;
  GlobalHomeTeamID: number;
  IsClosed: boolean;
  NeutralVenue: boolean;
  DateTimeUTC: string;
  GameEndDateTime: string;
  SeriesInfo?: SeriesInfo;
};

//teams
export type Team = {
  TeamID: number;
  Key: string;
  Active: boolean;
  City: string;
  Name: string;
  LeagueID: number;
  StadiumID: number;
  Conference: string;
  Division: string;
  PrimaryColor: string;
  SecondaryColor: string;
  TertiaryColor: string;
  QuaternaryColor: string;
  WikipediaLogoUrl: string | null;
  WikipediaWordMarkUrl: string | null;
  GlobalTeamID: number;
  NbaDotComTeamID: number;
  HeadCoach: string;
};

//Games
export type Game = {
  GameID: number;
  Season: number;
  SeasonType: number;
  Status: string;
  Day: string;
  DateTime: string;
  AwayTeam: string;
  HomeTeam: string;
  AwayTeamID: number;
  HomeTeamID: number;
  StadiumID: number;
  Channel: string | null;
  Attendance: number | null;
  AwayTeamScore: number | null;
  HomeTeamScore: number | null;
  Updated: string;
  Quarter: number | null;
  TimeRemainingMinutes: number | null;
  TimeRemainingSeconds: number | null;
  PointSpread: number | null;
  OverUnder: number | null;
  AwayTeamMoneyLine: number | null;
  HomeTeamMoneyLine: number | null;
  GlobalGameID: number;
  GlobalAwayTeamID: number;
  GlobalHomeTeamID: number;
  PointSpreadAwayTeamMoneyLine: number | null;
  PointSpreadHomeTeamMoneyLine: number | null;
  LastPlay: string | null;
  IsClosed: boolean;
  GameEndDateTime: string | null;
  HomeRotationNumber: number | null;
  AwayRotationNumber: number | null;
  NeutralVenue: boolean;
  OverPayout: number | null;
  UnderPayout: number | null;
  CrewChiefID: number | null;
  UmpireID: number | null;
  RefereeID: number | null;
  AlternateID: number | null;
  DateTimeUTC: string;
  InseasonTournament: boolean;
  SeriesInfo: unknown;
  Quarters: unknown[];
};

//Players/${abbr}?key=${process.env.API_KEY}
export type TeamPlayer = {
  PlayerID: number;
  SportsDataID: string;
  Status: string;
  TeamID: number;
  Team: TeamAbbreviation;
  Jersey: number;
  PositionCategory: string;
  Position: string;
  FirstName: string;
  LastName: string;
  Height: number;
  Weight: number;
  BirthDate: string;
  BirthCity: string;
  BirthState: string | null;
  BirthCountry: string;
  HighSchool: string | null;
  College: string | null;
  Salary: number | null;
  PhotoUrl: string;
  Experience: number;
  SportRadarPlayerID: string;
  RotoworldPlayerID: number | null;
  RotoWirePlayerID: number | null;
  FantasyAlarmPlayerID: number | null;
  StatsPlayerID: number | null;
  SportsDirectPlayerID: number | null;
  XmlTeamPlayerID: number | null;
  InjuryStatus: string;
  InjuryBodyPart: string;
  InjuryStartDate: string | null;
  InjuryNotes: string;
  FanDuelPlayerID: number | null;
  DraftKingsPlayerID: number | null;
  YahooPlayerID: number | null;
  FanDuelName: string | null;
  DraftKingsName: string | null;
  YahooName: string | null;
  DepthChartPosition: string | null;
  DepthChartOrder: number | null;
  GlobalTeamID: number;
  FantasyDraftName: string | null;
  FantasyDraftPlayerID: number | null;
  UsaTodayPlayerID: number | null;
  UsaTodayHeadshotUrl: string | null;
  UsaTodayHeadshotNoBackgroundUrl: string | null;
  UsaTodayHeadshotUpdated: string | null;
  UsaTodayHeadshotNoBackgroundUpdated: string | null;
  NbaDotComPlayerID: number | null;
};

//TeamSeasonStats
export type TeamStat = {
  StatID: number;
  TeamID: number;
  SeasonType: number;
  Season: number;
  Name: string;
  Team: TeamAbbreviation;
  Wins: number;
  Losses: number;
  OpponentPosition: string | null;
  Possessions: number;
  GlobalTeamID: number;
  Updated: string;
  Games: number;
  FantasyPoints: number;
  Minutes: number;
  Seconds: number;
  FieldGoalsMade: number;
  FieldGoalsAttempted: number;
  FieldGoalsPercentage: number;
  EffectiveFieldGoalsPercentage: number;
  TwoPointersMade: number;
  TwoPointersAttempted: number;
  TwoPointersPercentage: number;
  ThreePointersMade: number;
  ThreePointersAttempted: number;
  ThreePointersPercentage: number;
  FreeThrowsMade: number;
  FreeThrowsAttempted: number;
  FreeThrowsPercentage: number;
  OffensiveRebounds: number;
  DefensiveRebounds: number;
  Rebounds: number;
  OffensiveReboundsPercentage: number | null;
  DefensiveReboundsPercentage: number | null;
  TotalReboundsPercentage: number | null;
  Assists: number;
  Steals: number;
  BlockedShots: number;
  Turnovers: number;
  PersonalFouls: number;
  Points: number;
  TrueShootingAttempts: number;
  TrueShootingPercentage: number;
  PlayerEfficiencyRating: number | null;
  AssistsPercentage: number | null;
  StealsPercentage: number | null;
  BlocksPercentage: number | null;
  TurnOversPercentage: number | null;
  UsageRatePercentage: number | null;
  FantasyPointsFanDuel: number;
  FantasyPointsDraftKings: number;
  FantasyPointsYahoo: number;
  PlusMinus: number;
  DoubleDoubles: number;
  TripleDoubles: number;
  FantasyPointsFantasyDraft: number;
  IsClosed: boolean;
  LineupConfirmed: boolean | null;
  LineupStatus: string;
  OpponentStat: TeamStat | null;
};

//TeamGameStatsBySeason
export type TeamGameLog = {
  StatID: number;
  TeamID: number;
  SeasonType: number;
  Season: number;
  Name: string;
  Team: string;
  Wins: number;
  Losses: number;
  Possessions: number;
  GlobalTeamID: number;
  GameID: number;
  OpponentID: number;
  Opponent: TeamAbbreviation;
  Day: string;
  DateTime: string;
  HomeOrAway: "HOME" | "AWAY";
  IsGameOver: boolean;
  GlobalGameID: number;
  GlobalOpponentID: number;
  Updated: string;
  Games: number;
  FantasyPoints: number;
  Minutes: number;
  Seconds: number;
  FieldGoalsMade: number;
  FieldGoalsAttempted: number;
  FieldGoalsPercentage: number;
  EffectiveFieldGoalsPercentage: number;
  TwoPointersMade: number;
  TwoPointersAttempted: number;
  TwoPointersPercentage: number;
  ThreePointersMade: number;
  ThreePointersAttempted: number;
  ThreePointersPercentage: number;
  FreeThrowsMade: number;
  FreeThrowsAttempted: number;
  FreeThrowsPercentage: number;
  OffensiveRebounds: number;
  DefensiveRebounds: number;
  Rebounds: number;
  OffensiveReboundsPercentage: number | null;
  DefensiveReboundsPercentage: number | null;
  TotalReboundsPercentage: number | null;
  Assists: number;
  Steals: number;
  BlockedShots: number;
  Turnovers: number;
  PersonalFouls: number;
  Points: number;
  TrueShootingAttempts: number;
  TrueShootingPercentage: number;
  PlayerEfficiencyRating: number | null;
  AssistsPercentage: number | null;
  StealsPercentage: number | null;
  BlocksPercentage: number | null;
  TurnOversPercentage: number | null;
  UsageRatePercentage: number | null;
  FantasyPointsFanDuel: number;
  FantasyPointsDraftKings: number;
  FantasyPointsYahoo: number;
  PlusMinus: number;
  DoubleDoubles: number;
  TripleDoubles: number;
  FantasyPointsFantasyDraft: number;
  IsClosed: boolean;
  LineupConfirmed: boolean | null;
  LineupStatus: string;
};

//PlayersActiveBasic
export type Player = {
  PlayerID: number;
  SportsDataID: string;
  Status: string;
  TeamID: number;
  Team: TeamAbbreviation;
  Jersey: number | null;
  PositionCategory: string;
  Position: string;
  FirstName: string;
  LastName: string;
  BirthDate: string;
  BirthCity: string;
  BirthState: string;
  BirthCountry: string;
  GlobalTeamID: number;
  Height: number;
  Weight: number;
};

//Players?key=${process.env.API_KEY}
export type PlayerInfo = {
  PlayerID: number;
  SportsDataID: string;
  Status: string;
  TeamID: number;
  Team: TeamAbbreviation;
  Jersey: string | null;
  PositionCategory: string;
  Position: string;
  FirstName: string;
  LastName: string;
  Height: number;
  Weight: number;
  BirthDate: string;
  BirthCity: string;
  BirthState: string;
  BirthCountry: string;
  HighSchool: string | null;
  College: string;
  Salary: number;
  PhotoUrl: string;
  Experience: number;
  SportRadarPlayerID: string;
  RotoworldPlayerID: number;
  RotoWirePlayerID: number;
  FantasyAlarmPlayerID: number;
  StatsPlayerID: number;
  SportsDirectPlayerID: number;
  XmlTeamPlayerID: number;
  InjuryStatus: string;
  InjuryBodyPart: string;
  InjuryStartDate: string | null;
  InjuryNotes: string;
  FanDuelPlayerID: number;
  DraftKingsPlayerID: number;
  YahooPlayerID: number;
  FanDuelName: string;
  DraftKingsName: string;
  YahooName: string;
  DepthChartPosition: string;
  DepthChartOrder: number;
  GlobalTeamID: number;
  FantasyDraftName: string;
  FantasyDraftPlayerID: number;
  UsaTodayPlayerID: number;
  UsaTodayHeadshotUrl: string;
  UsaTodayHeadshotNoBackgroundUrl: string;
  UsaTodayHeadshotUpdated: string;
  UsaTodayHeadshotNoBackgroundUpdated: string;
  NbaDotComPlayerID: number;
};

//PlayerSeasonStats
export type PlayerSeasonStat = {
  StatID: number;
  TeamID: number;
  PlayerID: number;
  SeasonType: number;
  Season: number;
  Name: string;
  Team: TeamAbbreviation;
  Position: string;
  Started: number;
  GlobalTeamID: number;
  Updated: string;
  Games: number;
  FantasyPoints: number;
  Minutes: number;
  Seconds: number;
  FieldGoalsMade: number;
  FieldGoalsAttempted: number;
  FieldGoalsPercentage: number;
  EffectiveFieldGoalsPercentage: number;
  TwoPointersMade: number;
  TwoPointersAttempted: number;
  TwoPointersPercentage: number;
  ThreePointersMade: number;
  ThreePointersAttempted: number;
  ThreePointersPercentage: number;
  FreeThrowsMade: number;
  FreeThrowsAttempted: number;
  FreeThrowsPercentage: number;
  OffensiveRebounds: number;
  DefensiveRebounds: number;
  Rebounds: number;
  OffensiveReboundsPercentage: number;
  DefensiveReboundsPercentage: number;
  TotalReboundsPercentage: number;
  Assists: number;
  Steals: number;
  BlockedShots: number;
  Turnovers: number;
  PersonalFouls: number;
  Points: number;
  TrueShootingAttempts: number;
  TrueShootingPercentage: number;
  PlayerEfficiencyRating: number;
  AssistsPercentage: number;
  StealsPercentage: number;
  BlocksPercentage: number;
  TurnOversPercentage: number;
  UsageRatePercentage: number;
  FantasyPointsFanDuel: number;
  FantasyPointsDraftKings: number;
  FantasyPointsYahoo: number;
  PlusMinus: number;
  DoubleDoubles: number;
  TripleDoubles: number;
  FantasyPointsFantasyDraft: number;
  IsClosed: boolean;
  LineupConfirmed: string | null;
  LineupStatus: string;
};

//BoxScore

//.game
export type BoxScoreGame = {
  AlternateID: string | null;
  Attendance: number;
  AwayRotationNumber: number;
  AwayTeam: string;
  AwayTeamID: number;
  AwayTeamMoneyLine: number;
  AwayTeamScore: number;
  Channel: string;
  CrewChiefID: number;
  DateTime: string;
  DateTimeUTC: string;
  Day: string;
  GameEndDateTime: string;
  GameID: number;
  GlobalAwayTeamID: number;
  GlobalGameID: number;
  GlobalHomeTeamID: number;
  HomeRotationNumber: number;
  HomeTeam: string;
  HomeTeamID: number;
  HomeTeamMoneyLine: number;
  HomeTeamScore: number;
  InseasonTournament: boolean;
  IsClosed: boolean;
  LastPlay: string;
  NeutralVenue: boolean;
  OverPayout: number;
  OverUnder: number;
  PointSpread: number;
  PointSpreadAwayTeamMoneyLine: number;
  PointSpreadHomeTeamMoneyLine: number;
  Quarter: number | null;
  Quarters: BoxScoreQuarter[];
  RefereeID: number;
  Season: number;
  SeasonType: number;
  SeriesInfo: string | null;
  StadiumID: number;
  Status: string;
  TimeRemainingMinutes: number | null;
  TimeRemainingSeconds: number | null;
  UmpireID: number;
  UnderPayout: number;
  Updated: string;
};

//.playerGames
export type BoxScorePlayerGame = {
  Assists: number;
  AssistsPercentage: number;
  BlockedShots: number;
  BlocksPercentage: number;
  DateTime: string;
  Day: string;
  DefensiveRebounds: number;
  DefensiveReboundsPercentage: number;
  DoubleDoubles: number;
  DraftKingsPosition: string;
  DraftKingsSalary: number;
  EffectiveFieldGoalsPercentage: number;
  FanDuelPosition: string;
  FanDuelSalary: number;
  FantasyDataSalary: number;
  FantasyDraftPosition: string;
  FantasyDraftSalary: number | null;
  FantasyPoints: number;
  FantasyPointsDraftKings: number;
  FantasyPointsFanDuel: number;
  FantasyPointsFantasyDraft: number;
  FantasyPointsYahoo: number;
  FieldGoalsAttempted: number;
  FieldGoalsMade: number;
  FieldGoalsPercentage: number;
  FreeThrowsAttempted: number;
  FreeThrowsMade: number;
  FreeThrowsPercentage: number;
  GameID: number;
  Games: number;
  GlobalGameID: number;
  GlobalOpponentID: number;
  GlobalTeamID: number;
  HomeOrAway: "HOME" | "AWAY";
  InjuryBodyPart: string;
  InjuryNotes: string;
  InjuryStartDate: string | null;
  InjuryStatus: string;
  IsClosed: boolean;
  IsGameOver: boolean;
  LineupConfirmed: boolean;
  LineupStatus: string;
  Minutes: number;
  Name: string;
  OffensiveRebounds: number;
  OffensiveReboundsPercentage: number;
  Opponent: string;
  OpponentID: number;
  OpponentPositionRank: number;
  OpponentRank: number;
  PersonalFouls: number;
  PlayerEfficiencyRating: number;
  PlayerID: number;
  PlusMinus: number;
  Points: number;
  Position: string;
  Rebounds: number;
  Season: number;
  SeasonType: number;
  Seconds: number;
  Started: number;
  StatID: number;
  Steals: number;
  StealsPercentage: number;
  Team: TeamAbbreviation;
  TeamID: number;
  ThreePointersAttempted: number;
  ThreePointersMade: number;
  ThreePointersPercentage: number;
  TotalReboundsPercentage: number;
  TripleDoubles: number;
  TrueShootingAttempts: number;
  TrueShootingPercentage: number;
  TurnOversPercentage: number;
  Turnovers: number;
  TwoPointersAttempted: number;
  TwoPointersMade: number;
  TwoPointersPercentage: number;
  Updated: string;
  UsageRatePercentage: number;
  YahooPosition: string;
  YahooSalary: number;
};

//.quarter
export type BoxScoreQuarter = {
  AwayScore: number;
  GameID: number;
  HomeScore: number;
  Name: string;
  Number: number;
  QuarterID: number;
};

//.teamGames
export type BoxScoreTeamGame = {
  Assists: number;
  AssistsPercentage: number | null;
  BlockedShots: number;
  BlocksPercentage: number | null;
  DateTime: string;
  Day: string;
  DefensiveRebounds: number;
  DefensiveReboundsPercentage: number | null;
  DoubleDoubles: number;
  EffectiveFieldGoalsPercentage: number;
  FantasyPoints: number;
  FantasyPointsDraftKings: number;
  FantasyPointsFanDuel: number;
  FantasyPointsFantasyDraft: number;
  FantasyPointsYahoo: number;
  FieldGoalsAttempted: number;
  FieldGoalsMade: number;
  FieldGoalsPercentage: number;
  FreeThrowsAttempted: number;
  FreeThrowsMade: number;
  FreeThrowsPercentage: number;
  GameID: number;
  Games: number;
  GlobalGameID: number;
  GlobalOpponentID: number;
  GlobalTeamID: number;
  HomeOrAway: "HOME" | "AWAY";
  IsClosed: boolean;
  IsGameOver: boolean;
  LineupConfirmed: null | string;
  LineupStatus: string;
  Losses: number;
  Minutes: number;
  Name: string;
  OffensiveRebounds: number;
  OffensiveReboundsPercentage: number | null;
  Opponent: string;
  OpponentID: number;
  PersonalFouls: number;
  PlayerEfficiencyRating: number | null;
  PlusMinus: number;
  Points: number;
  Possessions: number;
  Rebounds: number;
  Season: number;
  SeasonType: number;
  Seconds: number;
  StatID: number;
  Steals: number;
  StealsPercentage: number | null;
  Team: TeamAbbreviation;
  TeamID: number;
  ThreePointersAttempted: number;
  ThreePointersMade: number;
  ThreePointersPercentage: number;
  TotalReboundsPercentage: number | null;
  TripleDoubles: number;
  TrueShootingAttempts: number;
  TrueShootingPercentage: number;
  TurnOversPercentage: number | null;
  Turnovers: number;
  TwoPointersAttempted: number;
  TwoPointersMade: number;
  TwoPointersPercentage: number;
  Updated: string;
  UsageRatePercentage: number | null;
  Wins: number;
};

export type FullBoxScore = {
  Game: BoxScoreGame;
  PlayerGames: BoxScorePlayerGame[];
  Quarters: BoxScoreQuarter[];
  TeamGames: BoxScoreTeamGame[];
};

//\\
export type ExtendedPlayerSeasonStat = PlayerSeasonStat & {
  pointsPerGame: number;
  assistsPerGame: number;
  reboundsPerGame: number;
  blocksPerGame: number;
  stealsPerGame: number;
  threesPerGame: number;
};
